Add JRuby 9.2.20.1
rvm/rvm pull request #5160
Opened 2021-12-01 16:59 UTC by headius

2021-12-01 17:52 UTC, pkuczynski approved these changes

2021-12-01 17:53 UTC, pkuczynski requested changes
Missing CHANGELOG entry

2022-01-19 17:17 UTC, headius commented
The changelog requirement is pretty cumbersome, since independent changes will conflict with each other and I have to create the PR before I can update the changelog. It seems like this section could be auto-generated based on the added versions, couldn't it?

2022-01-19 20:05 UTC, pkuczynski approved these changes

2022-01-19 20:07 UTC, pkuczynski commented
Thanks!

> The changelog requirement is pretty cumbersome

You could also do all 3 versions in one PR, we would not mind.

2022-01-19 20:07 UTC, merged