Fix CI
rvm/rvm pull request #5313
Opened 2023-02-14 15:35 UTC by mathieujobin

Changes proposed in this pull request:
* bump 2.4.0 on the prepare step. the gemset error is common with old rubies now...

- [ ] Make sure that your pull request includes entry in the [CHANGELOG](CHANGELOG.md).

2023-02-14 15:58 UTC, pkuczynski approved these changes
I think it makes sense to bump it and don't worry too much about old rubies. @mpapis @raelgc what do you think?

2023-02-14 17:18 UTC, raelgc approved these changes

2023-02-14 17:20 UTC, raelgc requested changes
CI is still failing about 2.6

2023-02-15 05:34 UTC, mathieujobin commented
progress
![image](https://user-images.githubusercontent.com/99191/218941514-6f7947b1-554f-49e1-8ec6-e24b05cb1322.png)

2023-02-15 13:34 UTC, mathieujobin commented
I'd like some help on this one... 

macos-latest all pass, no errors.

https://github.com/rvm/rvm/actions/runs/4181029459/jobs/7242562592

ubuntu, the 970 test cases finally also passed...

but on the following step, tf command is reported as not found... makes no sense,.. since its available in the step above

I guess, that step is skipped on macos, so maybe we could skip as well.

2023-02-16 00:33 UTC, mathieujobin commented
@larskanis I have not seen any failure caused by gem-empty.. and all test pass now
@pkuczynski We can merge this...

2023-02-16 10:30 UTC, pkuczynski approved these changes

2023-02-16 10:30 UTC, merged